version: '3.8'
volumes:
  redis: {}
services:
  redis:
    image: docker.io/redis:7.0.11-alpine3.17
    volumes:
      - redis:/data
    network_mode: host
    command:
      - redis-server
      - --save
      - 60
      - 1
      - --loglevel
      - warning
